# ----
# Site

title: Neural Extraction Framework
url: "https://ananyaiitbhilai.github.io/DBpedia_GSoC2022_Neural_Extraction_Framework/"
baseurl: 
google_analytics_key:
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /images/siteicon.png
description: Weekly Blogs for Neural Extraction Framework Project.
author: 
  name: Ananya
  email: ananyah@iitbhilai.ac.in
  twitter: # twitter username without the @ symbol
social:
  name: GSoC 2022
  links:
    - https://github.com/dbpedia/neural-extraction-framework

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major
